sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t demodockeracc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true demodockeracc/docker-react npm run test 